### Generated by rprotoc. DO NOT EDIT!
### <proto file: protocol.proto>
# package protobuf;
# 
# message MixMessage {
#   required string addr = 1;
#   required bytes iv = 2;
#   required bytes key = 3;
#   required bytes msg = 4;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Protobuf
  class MixMessage < ::Protobuf::Message
    defined_in __FILE__
    required :string, :addr, 1
    required :bytes, :iv, 2
    required :bytes, :key, 3
    required :bytes, :msg, 4
  end
end